name: Download AdGuard Home Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull AdGuard Home Image
        run: docker pull --pull always adguard/adguardhome:latest

      - name: Save to File
        run: docker save -o adguardhome-latest.tar adguard/adguardhome:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: adguardhome-image
          path:  adguardhome-latest.tar
          retention-days: 1
