name: Download Portainer Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Portainer Image
        run: docker pull portainer/portainer-ce:latest

      - name: Save to File
        run: docker save -o portainer-latest.tar portainer/portainer-ce:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Portainer-image
          path: portainer-latest.tar
          retention-days: 1
